Docs/Air/POP/POP - POP은 OOP(Object-Oriented)와 어떤 점에서 철학이 다를까?.md

- **주차:** [Week 1]
- **주제:** "POP은 OOP(Object-Oriented)와 어떤 점에서 철학이 다를까?"
- **관련 이슈:** #12 
- 알게 된 점 1. POP도 OOP와 같이 코드 재사용성과 유지보수성을 늘리기 위한 목표를 가지고 만들어진 프로그래밍 패러다임이다.
- 알게 된 점 2. 프로토콜은 값 타입에서도 사용할 수 있기 때문에 구조체를 많이 사용하는 SwiftUI에서 유용하게 사용된다.
1. 궁금한 점 1 프로토콜 지향 프로그래밍을 지원하는 또 다른 프로그래밍 언어에는 어떤 것이 있을까?

feat: POP - POP은 OOP(Object-Oriented)와 어떤 점에서 철학이 다를까?

---

Docs/Noter/Optional - Swift는 왜 Optional이라는 개념을 언어 레벨에서 강제했을까?.md
Docs/Noter/POP - Swift가 Protocol-Oriented를 강조한 이유는 무엇일까?.md

- **주차:** [Week 1]
- **주제:** "Swift는 왜 Optional이라는 개념을 언어 레벨에서 강제했을까?"
- **관련 이슈:** #12 
1. 옵셔널 체이닝(a?.b?.c)은 내부적으로 어떻게 작동할까?
2. 옵셔널은 어떻게 메모리에 저장되고 동작할까? 실제로는 열거형?

[gq] #12: Optional - Swift는 왜 Optional이라는 개념을 언어 레벨에서 강제했을까?

---

Docs/Air/Swift-Concurrency/Swift-Concurrency - Task와 Task.detached의 차이는 무엇이며, 각각 언제 써야 할까?.md

- **주차:** [Week 2]
- **주제:** "Swift-Concurrency - Task와 Task.detached의 차이는 무엇이며, 각각 언제 써야 할까?"
- **관련 이슈:** #38 
- 알게 된 점 1. Task는 현재의 실행 컨텍스트(context), 우선순위, actor 상태를 상속받아서 실행된다. 그래서 actor 내부나 UI 관련 작업에서 안전하게 사용할 수 있다.
- 알게 된 점 2. Task.detached는 완전히 독립적으로 실행되며, 현재 context를 상속받지 않는다. 따라서 actor 외부나 백그라운드에서 실행할 때 유용하지만, 상태 접근 시 반드시 await가 필요하다.
- 알게 된 점 3. actor 내부에서 Task.detached를 사용하면 내부 상태에 직접 접근할 수 없고, await self 형식으로 안전하게 접근해야 한다. 그렇지 않으면 데이터 경쟁이나 크래시 위험이 있다.
- 알게 된 점 4. Task는 구조화된, 부모와 연결된 작업에 적합하고, Task.detached는 완전히 분리된 백그라운드 작업에 적합하다. 상황에 맞게 구분해서 써야 한다.
1. Task.detached는 actor context도 안 따라오고 취소도 안 되면, 어떻게 취소 처리하거나 제어할 수 있을까?

[gq] #38: Swift-Concurrency - Task와 Task.detached의 차이는 무엇이며, 각각 언제 써야 할까?

---

Docs/Nika/Concurrency - Race condition은 어떤 경우에 생기고, Swift에서는 어떻게 방지할 수 있을까?.md

- **주차:** [Week ?]
- **주제:** "열거형, 병렬처리"
- **관련 이슈:** #38 
- 알게 된 점 1. race condition의 개념
- 알게 된 점 2. race condition을 막기 위해 swift에서 실천할 수 있는 여러 가지 방법
- 알게 된 점 3.
- 알게 된 점 4.
1. 궁금한 점 1
1. 궁금한 점 2

38/Nika-Concurrency - Race condition은 어떤 경우에 생기고, Swift에서는 어떻게 방지할 수 있을까?

---

Docs/Air/Data-Modeling/Data Modeling - 데이터 모델링 단계에서 발생할 수 있는 성능 병목 현상을 어떻게 예측하고 완화할 수 있는가?.md

- **주차:** [Week 3]
- **주제:** "데이터 모델링 단계에서 발생할 수 있는 성능 병목 현상(예: 조인 비용, 인덱스 선택 오류 등)을 어떻게 예측하고 완화할 수 있는가?"
- **관련 이슈:** #57 
- 알게 된 점 1. 관계 데이터 프리페치를 활용하면 관계 있는 데이터 모델을 함께 가져와 더 효율적으로 데이터를 읽을 수 있다.
- 알게 된 점 2. Core Data에 모델 필드 중 자주 검색되는 필드에 indexed를 설정하여 쿼리 속도를 개선할 수 있다.
- 알게 된 점 3. 대량의 데이터를 fetch 할 때 Batch Fetch, Faulting을 활용하여 메모리 사용량을 크게 줄일 수 있다.
- 알게 된 점 4. Background Context를 활용하면 비동기로 저장이 가능하다.
1. 성능 병목 현상을 예측하는 방법에 대해서는 더 알아봐야겠다...

[gq] #57: Data Modeling - 데이터 모델링 단계에서 발생할 수 있는 성능 병목 현상을 어떻게 예측하고 완화할 수 있는가?

---

Docs/Sera/Swift Standard Library/Sequence와 Collection의 차이점은 무엇이고, 각각의 사용 사례는 어떤 것이 있는가?.md

- **주차:** [Week ?]
- **주제:** "엔티티-관계 다이어그램(ERD)에서 Entity, Attribute, Relationship을 정의할 때 고려해야 할 주요 설계 원칙은 무엇인가?"
- **관련 이슈:** #57
- 알게 된 점 1.
- 알게 된 점 2.
- 알게 된 점 3.
- 알게 된 점 4.
1. 궁금한 점 1
1. 궁금한 점 2

Data Modeling

---

Docs/Air/LLVM-Compiler/LLVM Compiler- LLVM Intermediate Representation LLVM IR이란 무엇이며 어떤 특징을 가지고 있는가.md

- **주차:** [Week 4]
- **주제:** "LLVM Intermediate Representation LLVM IR이란 무엇이며 어떤 특징을 가지고 있는가"
- **관련 이슈:** #72 
- 알게 된 점 1. Swift 코드는 SIL -> LLVM IR -> 기계어 단계로 변환된다.
- 알게 된 점 2. LLVM IR도 추상화되어 있기 때문에 여러 CPU 아키텍처에 대응 가능하다.
1. Swift 코드를 변환한 LLVM IR과 다른 프로그래밍 언어로 작성한 코드를 변환한 LLVM IR은 차이가 있을까?

LLVM Intermediate Representation LLVM IR이란 무엇이며 어떤 특징을 가지고 있는가

---

Docs/Zhen/RegularExpressionDSL - 정규식 최적화 이론 관점에서 매칭 속도를 높이기 위해 적용할 수 있는 기법들(예 길이 기반 프리스크리닝 그리디 vs 레이지 매칭 조정 등)과 그 원리는 무엇인가.md

- **주차:** [Week 5]
- **주제:** "정규식 최적화 이론 관점에서 매칭 속도를 높이기 위해 적용할 수 있는 기법들(예 길이 기반 프리스크리닝 그리디 vs 레이지 매칭 조정 등)과 그 원리는 무엇인가"
- **관련 이슈:** #78 
- 알게 된 점 1. 그냥 정규식을 쓰는 것보다 정규식을 효율적으로 쓰기 위한 노력이 필요하구나... 
- 알게 된 점 2. 근데 그게 어렵구나.........
1. 궁금한 점: 문자열이 길 때만 고려하면 되는걸까? 어떨 때 이걸 고려해야 하는거지?

[gq] #72 정규식 DSL  : 정규식 최적화 이론 관점에서 매칭 속도를 높이기 위해 적용할 수 있는 기법들(예 길이 기반 프리스크리닝 그리디 vs 레이지 매칭 조정 등)과 그 원리는 무엇인가 

---

Docs/Zhen/MainActor - MainActor는 Swift에서 어떤 역할을 하며 메인 스레드와 어떻게 연결되는가.md

- **주차:** [Week 6]
- **주제:** "UI 업데이트를 안전하게 보장하기 위해 MainActor를 어떤 방식으로 활용하면 좋을까"
- **관련 이슈:** #88 
- 알게 된 점 1. MainActor 는 내부적으로 GlobalActor 로 정의되어 있고, GlobalActor 는 사용자가 직접 정의하는 Actor 어노테이션임. 
- 알게 된 점 2. MainActor 는 메인 스레드에서 작업하도록 강제하기 때문에 UI 업데이트를 안전하게 보장.

[GQ] MainActor는 Swift에서 어떤 역할을 하며 메인 스레드와 어떻게 연결되는가, UI 업데이트를 안전하게 보장하기 위해 MainActor를 어떤 방식으로 활용하면 좋을까

---

Docs/Noter/Concurrency - MainActor는 UI 업데이트에서 어떤 역할을 하며, 왜 중요한가?.md
Docs/Noter/MainActor/MainActor - MainActor와 Task의 조합은 어떤 문제를 일으킬 수 있는가.md

- **주차:** [Week 5]
- **주제:** "MainActor와 Task의 조합은 어떤 문제를 일으킬 수 있는가"
- **관련 이슈:** #88 
- 알게 된 점 1. MainActor와 Task가 조합될 때와 같이 컨텍스트 전환이 많이 일어나는 부분은 주의해서 코드를 짜야겠구나!
- 알게 된 점 2. 불필요한 hop를 줄이고 필요한 곳에만 명시적으로 @MainActor를 선언해 써야겠다!

[gq] #88: MainActor - MainActor와 Task의 조합은 어떤 문제를 일으킬 수 있는가

---

Docs/Air/Frameworks/Apple Foundation Model - Apple Foundation Model의 사용법을 알아보자.md

- **주차:** [Week 6]
- **주제:** "Apple Foundation Model - Apple Foundation Model의 사용법을 알아보자"
- **관련 이슈:** #101 
- 알게 된 점 1. Apple Foundation Model은 Generative Model 기능을 제공한다
- 알게 된 점 2. Apple Foundation Model은 Tool Calling 기능을 제공한다.
1. 궁금한 점 1
1. 궁금한 점 2

[gq] #101: Apple Foundation Model - Apple Foundation Model의 사용법을 알아보자

---

Docs/Air/ARC/ARC - ARC 기반 앱의 메모리 누수를 Instruments(Leaks, Allocations 등)를 사용해 어떻게 진단하고 추적할 수 있는가?.md

… 추적할 수 있는가?
- **주차:** [Week 6]
- **주제:** "ARC 기반 앱의 메모리 누수를 Instruments(Leaks, Allocations 등)를 사용해 어떻게 진단하고 추적할 수 있는가?"
- **관련 이슈:** #101 
- 알게 된 점 1. Instruments로 메모리 사용량 추적하는 법
1. 궁금한 점 1
1. 궁금한 점 2

[gq] #101: ARC 기반 앱의 메모리 누수를 Instruments(Leaks, Allocations 등)를 사용해 어떻게 진단하고 추적할 수 있는가?

---

Docs/Air/Frameworks/AVFoundation - 앱에서 동영상을 어떻게 재생할 수 있을까?.md

- **주차:** [Week 7]
- **주제:** "앱에서 동영상을 어떻게 재생할 수 있을까?"
- **관련 이슈:** #112 
- 알게 된 점 1. AVFoundation을 사용하면 동영상 재생, 녹화, 편집, 분석이 가능하다.
- 알게 된 점 2. AVFoundation의 AVPlayer나 AVPlayerViewController는 UIKit으로 구현해야 한다.
- 알게 된 점 3. SwiftUI에는 VideoPlayer라는 게 있다.
1. SwiftUI로 사용할 수 있는 VideoPlayer의 사용법과 한계는?

[gq] #112: AVFoundation - 앱에서 동영상을 어떻게 재생할 수 있을까?

---

Docs/Air/Type-Casting/Type Casting - 프로토콜 타입과의 캐스팅은 어떻게 이뤄지는가? as?, as!, as의 사용 예시는.md

- **주차:** [Week 7]
- **주제:** "프로토콜 타입과의 캐스팅은 어떻게 이뤄지는가? as?, as!, as의 사용 예시는"
- **관련 이슈:** #112 
- 알게 된 점 1. 프로토콜과 함께 사용될 때, 타입 캐스팅은 Swift의 다형성을 극대화하고 유연한 설계를 가능하게 하는 필수적인 도구가 된다.
1. 궁금한 점 1
1. 궁금한 점 2

[gq] #112: Type Casting - 프로토콜 타입과의 캐스팅은 어떻게 이뤄지는가? as? as as의 사용 예시는

---

Docs/Nika/ARKit - 현실에 3D 오브젝트 띄우기.md
Docs/Nika/Type Casting - Any와 AnyObject는 어떤 상황에서 사용되며, 이들과 타입 캐스팅은 어떻게 관련되는가?.md

- **주차:** [Week ?]
- **주제:** "내용"
- **관련 이슈:** #이슈번호
- 알게 된 점 1. raycast 키워드
- 알게 된 점 2. AnyObject와 Any의 차이와 사용 목적
- 알게 된 점 3.
- 알게 된 점 4.
1. 궁금한 점 1
1. 궁금한 점 2

[gq] #112 ARKit - 현실에 3D 오브젝트 띄우기, Type Casting - Any와 AnyObject는 어떤 상황에서 사용되며, 이들과 타입 캐스팅은 어떻게 관련되는가?

---

Docs/Air/Access-Control/Access Control - Swift 모듈(Module)과 접근 레벨의 관계는?.md

- **주차:** [Week 8]
- **주제:** "Swift 모듈(Module)과 접근 레벨의 관계는?"
- **관련 이슈:** #127 
- 알게 된 점 1. Swift는 6단계의 접근 레벨을 제공한다.
- 알게 된 점 2. 이 접근 레벨들을 모듈 개발 시에 적절히 활용하면 프레임워크 API에 개발자의 의도를 잘 나타낼 수 있다.
- 알게 된 점 3. 캡슐화 설계에 아주 유용하다.
1. Swift로 모듈 개발은 어떻게 하는가?

[gq] #127: Access Control - Swift 모듈(Module)과 접근 레벨의 관계는?

---

Docs/Zhen/Access Control - 프레임워크를 배포할 때 어떤 접근 레벨을 주로 사용해야 할까요?.md

- **주차:** [Week 11]
- **주제:** "프레임워크를 배포할 때 어떤 접근 레벨을 주로 사용해야 할까요? "
- **관련 이슈:** #127 
- 알게 된 점 1. open, internal, fileprivate 이라는게 있구나~ 
- 알게 된 점 2. 캡슐화를 위해서 이렇게 나누는거구나 ~ 
1. 궁금한 점  실제로 사용한거 보고싶다 ~
2. 프로토콜 확장에서의 접근레벨은 어떻게 될까요~? 섞어서 쓸 수 있을까요?

[GQ] AC - 프레임워크를 배포할 때 어떤 접근 레벨을 주로 사용해야 할까요? 

---

Docs/Air/Higher-Order-Functions/Higher-Order Functions - Swift에서 compactMap과 flatMap의 차이점은 무엇이며, 각각 어떤 상황에서 유용하게 사용될 수 있을까요?.md

…용하게 사용될 수 있을까요?
- **주차:** [Week 9]
- **주제:** "compactMap과 flatMap의 차이점은 무엇이며, 각각 어떤 상황에서 유용하게 사용될 수 있을까요?"
- **관련 이슈:** #136 
- 알게 된 점 1. compactMap과 flatMap의 역할
1. 궁금한 점 1
1. 궁금한 점 2

[gq] #136: Higher-Order Functions - compactMap과 flatMap의 차이점은 무엇이며, 각각 어떤 상황에서 유용하게 사용될 수 있을까요?

---

Docs/Noter/Combine/Publisher와 Subscriber의 역할과 관계는 무엇인가?.md

- **주차:** [Week 10]
- **주제:** "Publisher와 Subscriber의 역할과 관계는 무엇인가?"
- **관련 이슈:** #142 
1. 궁금한 점 1
1. 궁금한 점 2

[gq] Publisher와 Subscriber의 역할과 관계는 무엇인가?

---

Docs/Air/Combine/Combine - Combine의 체이닝 연산자(map, filter, debounce 등)는 어떻게 동작하며, 언제 어떤 것을 사용하는가?.md

…것을 사용하는가?
- **주차:** [Week 10]
- **주제:** "Combine의 체이닝 연산자(map, filter, debounce 등)는 어떻게 동작하며, 언제 어떤 것을 사용하는가?"
- **관련 이슈:** #142 
- 알게 된 점 1. Combine에는 다양한 체이닝 연산자들이 존재하구나...
- 알게 된 점 2. 다양하게 쓸모가 많구나...
1. Combine 더 잘 쓰기

[gq] Combine - Combine의 체이닝 연산자(map, filter, debounce 등)는 어떻게 동작하며, 언제 어떤 것을 사용하는가?

---

Docs/Nika/Combine - Combine에서의 에러 처리 흐름은 어떻게 설계되어 있는가? (Failure, catch, replaceError, 등).md

- **주차:** [Week 10]
- **주제:** combine
- **관련 이슈:** #142 
- 알게 된 점 1.
- 알게 된 점 2.
- 알게 된 점 3.
- 알게 된 점 4.
1. 궁금한 점 1
1. 궁금한 점 2

[gq] Combine에서의 에러 처리 흐름은 어떻게 설계되어 있는가? (Failure, catch, replaceError, 등)

---

Docs/Hama/DesignPattern - Design Pattern이 뭐고, 왜 써야하는가?.md

- **주차:** [Week 12]
- **주제:** "Design Pattern이 뭐고, 왜 써야하는가?"
- **관련 이슈:** #158 
- 알게 된 점 1. 디자인 패턴이란, 여러 개발자가 반복해서 맞닥뜨린 문제를 해결하는 과정에서 발견된 공통적인 모범 답안을 정리한 것.
- 알게 된 점 2. 디자인 패턴 자체가 개발자들 사이의 공통된 어휘로 기능하기도 하다.
1. 궁금한 점 1 
1. 궁금한 점 2

[gq] Design Pattern - Design Pattern이 뭐고, 왜 써야하는가?

---

Docs/Air/Design-Pattern/Design Pattern - 팩토리 패턴은 어떤 장점을 가지며 어떻게 적용할 수 있을까?.md

- **주차:** [Week 12]
- **주제:** "Design Pattern - 팩토리 패턴은 어떤 장점을 가지며 어떻게 적용할 수 있을까?"
- **관련 이슈:** #158 
- 알게 된 점 1. 팩토리 패턴을 적용하면 객체를 사용하는 코드와 실제 생성되는 구체적인 클래스 간의 의존성이 줄어들고 결합도가 감소한다.
- 알게 된 점 2. 객체 생성 로직이 복잡한 경우 이를 추상화하여 감출 수 있다.
1. 궁금한 점 1
1. 궁금한 점 2

[gq] Design Pattern - 팩토리 패턴은 어떤 장점을 가지며 어떻게 적용할 수 있을까?

---

Docs/Nika/Animation - 레퍼런스 따라하기.md

- **주차:** [Week ?]
- **주제:** "내용"
- **관련 이슈:** #163 
- 알게 된 점 1. 애니메이션은 힘든 것이다...
- 알게 된 점 2.
- 알게 된 점 3.
- 알게 된 점 4.
1. 궁금한 점 1
1. 궁금한 점 2

#163 - Animation - 레퍼런스 따라하기

---

Docs/Noter/Animation/Animation - 버튼에 다양한 애니메이션을 적용해보자.md

- **주차:** [Week 13]
- **주제:** "SwiftUI Animation"
- **관련 이슈:** #163

[gq] SwiftUI Animation - 버튼에 다양한 애니메이션을 적용해보자
